# Generated by Django 2.0 on 2021-04-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintain',
            name='pmethod',
            field=models.CharField(max_length=20),
        ),
    ]
