# Generated by Django 3.2.5 on 2021-07-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageapp', '0004_alter_complain_ctitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='DateE',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addevent',
            name='Fund',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addevent',
            name='NEvent',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='addevent',
            name='TEvent',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addevent',
            name='Venue',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='complain',
            name='Name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complain',
            name='ctitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guest',
            name='VName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guest',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maintain',
            name='Month',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='maintain',
            name='Name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='maintain',
            name='pmethod',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Month',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rent',
            name='pmethod',
            field=models.CharField(max_length=30),
        ),
    ]
